[tool.poetry]
name = "lakehouse-insights"
version = "0.1.0"
description = ""
authors = ["JesusGavilan <jegavilgar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
deltalake = "0.16.4"
pyspark = "3.3.1"
delta-spark = "2.1.1"
streamlit = "1.29.0"
pytest = "^7.4.3"
streamlit-shadcn-ui = "0.1.18"
polars = "^1.8.2"
pyiceberg = {extras = ["pyarrow", "sql-sqlite"], version = "^0.7.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
